services:
  # MongoDB Primary Node - 初始化模式（无认证）
  mongo-primary:
    image: mongo:4.4
    container_name: mongo-primary
    hostname: mongo-primary
    restart: unless-stopped
    ports:
      - "${MONGO_BIND_IP}:${MONGO_PRIMARY_PORT}:27017"
    command: >
      sh -c "
      chmod 600 /etc/security/mongo-keyfile &&
      chown mongodb:mongodb /etc/security/mongo-keyfile &&
      mongod 
      --replSet ${REPLICA_SET_NAME}
      --bind_ip_all
      --wiredTigerCacheSizeGB=${MONGO_CACHE_SIZE_GB_PRIMARY}
      --oplogSize ${MONGO_OPLOG_SIZE_MB}
      "
    volumes:
      - mongo_primary_data:/data/db
      - mongo_primary_config:/data/configdb
      - mongo_logs:/var/log/mongodb
      - ./backups:/backup
      - ./config/mongod.conf:/etc/mongod.conf:ro
      - ./config/security/mongo-keyfile:/etc/security/mongo-keyfile
    environment:
      TZ: ${TZ}
    networks:
      - mongo-cluster
    deploy:
      resources:
        limits:
          memory: ${PRIMARY_MEMORY_LIMIT}
          cpus: '${PRIMARY_CPU_LIMIT}'
        reservations:
          memory: ${PRIMARY_MEMORY_RESERVATION}
          cpus: '${PRIMARY_CPU_RESERVATION}'

  # MongoDB Secondary Node 1 - 初始化模式
  mongo-secondary1:
    image: mongo:4.4
    container_name: mongo-secondary1
    hostname: mongo-secondary1
    restart: unless-stopped 
    ports:
      - "${MONGO_BIND_IP}:${MONGO_SECONDARY1_PORT}:27017"
    command: >
      sh -c "
      chmod 600 /etc/security/mongo-keyfile &&
      chown mongodb:mongodb /etc/security/mongo-keyfile &&
      mongod 
      --replSet ${REPLICA_SET_NAME}
      --bind_ip_all
      --wiredTigerCacheSizeGB=${MONGO_CACHE_SIZE_GB_SECONDARY}
      --oplogSize ${MONGO_OPLOG_SIZE_MB}
      "
    volumes:
      - mongo_secondary1_data:/data/db
      - mongo_secondary1_config:/data/configdb
      - mongo_logs_s1:/var/log/mongodb
      - ./backups:/backup
      - ./config/mongod.conf:/etc/mongod.conf:ro
      - ./config/security/mongo-keyfile:/etc/security/mongo-keyfile
    environment:
      TZ: ${TZ}
    networks:
      - mongo-cluster
    depends_on:
      - mongo-primary
    deploy:
      resources:
        limits:
          memory: ${SECONDARY_MEMORY_LIMIT}
          cpus: '${SECONDARY_CPU_LIMIT}'
        reservations:
          memory: ${SECONDARY_MEMORY_RESERVATION}
          cpus: '${SECONDARY_CPU_RESERVATION}'

  # MongoDB Secondary Node 2 - 初始化模式
  mongo-secondary2:
    image: mongo:4.4
    container_name: mongo-secondary2
    hostname: mongo-secondary2
    restart: unless-stopped
    ports:
      - "${MONGO_BIND_IP}:${MONGO_SECONDARY2_PORT}:27017"
    command: >
      sh -c "
      chmod 600 /etc/security/mongo-keyfile &&
      chown mongodb:mongodb /etc/security/mongo-keyfile &&
      mongod 
      --replSet ${REPLICA_SET_NAME}
      --bind_ip_all
      --wiredTigerCacheSizeGB=${MONGO_CACHE_SIZE_GB_SECONDARY}
      --oplogSize ${MONGO_OPLOG_SIZE_MB}
      "
    volumes:
      - mongo_secondary2_data:/data/db
      - mongo_secondary2_config:/data/configdb
      - mongo_logs_s2:/var/log/mongodb
      - ./backups:/backup
      - ./config/mongod.conf:/etc/mongod.conf:ro
      - ./config/security/mongo-keyfile:/etc/security/mongo-keyfile
    environment:
      TZ: ${TZ}
    networks:
      - mongo-cluster
    depends_on:
      - mongo-primary
    deploy:
      resources:
        limits:
          memory: ${SECONDARY_MEMORY_LIMIT}
          cpus: '${SECONDARY_CPU_LIMIT}'
        reservations:
          memory: ${SECONDARY_MEMORY_RESERVATION}
          cpus: '${SECONDARY_CPU_RESERVATION}'

volumes:
  mongo_primary_data:
    driver: local
  mongo_primary_config:
    driver: local
  mongo_secondary1_data:
    driver: local
  mongo_secondary1_config:
    driver: local
  mongo_secondary2_data:
    driver: local
  mongo_secondary2_config:
    driver: local
  mongo_logs:
    driver: local
  mongo_logs_s1:
    driver: local
  mongo_logs_s2:
    driver: local

networks:
  mongo-cluster:
    driver: bridge 